[package]
name = "tonic-web-wasm-client"
version = "0.1.2"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
license = "MIT/Apache-2.0"
description = "grpc-web implementation for use by tonic clients in browsers via webassembly"
homepage = "https://github.com/devashishdxt/tonic-web-wasm-client"
repository = "https://github.com/devashishdxt/tonic-web-wasm-client"
readme = "README.md"
categories = ["web-programming", "network-programming", "asynchronous"]
keywords = ["grpc", "grpc-web", "tonic", "wasm"]
edition = "2021"

[features]
default = ["console_error_panic_hook"]

[dependencies]
base64 = "0.13.0"
bytes = "1.1.0"
console_error_panic_hook = { version = "0.1.7", optional = true }
futures-core = "0.3.21"
http = "0.2.8"
http-body = "0.4.5"
httparse = "1.7.1"
reqwest = { version = "0.11.11", default-features = false }
thiserror = "1.0.31"
tonic = { version = "0.7.2", default-features = false }
tower = { version = "0.4.13", default-features = false }
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.31"
